version: '3'
services:

  db:
    container_name: blog_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5

  blog:
    container_name: blog_app
    image: wordpress:4.6
    environment:
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_HOST
    depends_on:
      - db
    ports:
      - "${BLOG_PORT}:80"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5

  kali:
    container_name: kali_linux
    build: docker/kali
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
